<?php
/**
 * 转场效表
 * 
 * @author wangwei
 */
return array(
	'对角切换' => 'directional',
	'旋涡' => 'displacement',
	'栅格' => 'windowslice',
	'垂直领结' => 'bowTieVertical',
	'水平领结' => 'bowTieHorizontal',
	'放大消失' => 'simplezoom',
	'线性模糊' => 'linearblur',
	'水滴' => 'waterdrop',
	'故障' => 'glitchmemories',
	'波点' => 'polka',
	'蔓延' => 'perlin',
	'扭曲旋转' => 'directionalwarp',
	'向上弹动' => 'bounce_up',
	'向下弹动' => 'bounce_down',
	'向右擦除' => 'wiperight',
	'向左擦除' => 'wipeleft',
	'向下擦除' => 'wipedown',
	'向上擦除' => 'wipeup',
	'雪花消除' => 'morph',
	'色彩溶解' => 'colordistance',
	'圆形遮罩' => 'circlecrop',
	'中心旋转' => 'swirl',
	'轻微摇摆' => 'dreamy',
	'多格翻转' => 'gridflip',
	'圆形放大' => 'zoomincircles',
	'圆形扫描' => 'radial',
	'相册' => 'mosaic',
	'波形放大' => 'undulatingburnout',
	'线性溶解' => 'crosshatch',
	'太空波纹' => 'crazyparametricfun',
	'万花筒' => 'kaleidoscope',
	'百叶窗' => 'windowblinds',
	'蜂巢溶解' => 'hexagonalize',
	'故障交替' => 'glitchdisplace',
	'炫境' => 'dreamyzoom',
	'齿状上升' => 'doomscreentransition_up',
	'齿状下落' => 'doomscreentransition_down',
	'波纹' => 'ripple',
	'风车' => 'pinwheel',
	'时钟旋转' => 'angular',
	'燃烧' => 'burn',
	'椭圆遮罩' => 'circle',
	'椭圆溶解' => 'circleopen',
	'色相溶解' => 'colorphase',
	'隧道扭曲' => 'crosswarp',
	'立方体' => 'cube',
	'渐变擦除' => 'directionalwipe',
	'开幕' => 'doorway',
	'渐隐' => 'fade',
	'彩色渐隐' => 'fadecolor',
	'灰色渐隐' => 'fadegrayscale',
	'回忆' => 'flyeye',
	'爱心遮罩' => 'heart',
	'对角开幕' => 'luma',
	'多层混合' => 'multiplyblend',
	'像素溶解' => 'pixelize',
	'花瓣遮罩' => 'polarfunction',
	'随机方块' => 'randomsquares',
	'旋转' => 'rotatescalefade',
	'方块替换' => 'squareswire',
	'向内推入' => 'squeeze',
	'切入' => 'swap',
	'线形擦除' => 'wind',
);