<?php
/**
 * 演员配音
 * 
 * @author wangwei
 */
return array(
	'多情感' => 
'情感|冷酷哥哥（多情感）|zh_male_lengkugege_emo_v2_mars_bigtts|中文|生气、冷漠、恐惧、开心、厌恶、中性、悲伤、沮丧|否
甜心小美（多情感）|zh_female_tianxinxiaomei_emo_v2_mars_bigtts|中文|悲伤、恐惧、厌恶、中性|剪映|否
高冷御姐（多情感）|zh_female_gaolengyujie_emo_v2_mars_bigtts|中文|开心、悲伤、生气、惊讶、恐惧、厌恶、激动、冷漠、中性|剪映|否
傲娇霸总（多情感）|zh_male_aojiaobazong_emo_v2_mars_bigtts|中文|中性、开心、愤怒、厌恶|剪映|否
广州德哥（多情感）|zh_male_guangzhoudege_emo_mars_bigtts|中文|生气、恐惧、中性|剪映|是
京腔侃爷（多情感）|zh_male_jingqiangkanye_emo_mars_bigtts|中文|开心、生气、惊讶、厌恶、中性|剪映|是
邻居阿姨（多情感）|zh_female_linjuayi_emo_v2_mars_bigtts|中文|中性、愤怒、冷漠、沮丧、惊讶|剪映|否
优柔公子（多情感）|zh_male_yourougongzi_emo_v2_mars_bigtts|中文|开心、生气、恐惧、厌恶、激动、中性、沮丧|剪映|否
儒雅男友（多情感）|zh_male_ruyayichen_emo_v2_mars_bigtts|中文|开心、悲伤、生气、恐惧、激动、冷漠、中性|剪映|否
俊朗男友（多情感）|zh_male_junlangnanyou_emo_v2_mars_bigtts|中文|开心、悲伤、生气、惊讶、恐惧、中性|剪映|否
北京小爷（多情感）|zh_male_beijingxiaoye_emo_v2_mars_bigtts|中文|生气，惊讶，恐惧，激动，冷漠，中性|否
柔美女友（多情感）|zh_female_roumeinvyou_emo_v2_mars_bigtts|中文|开心，悲伤，生气，惊讶，恐惧，厌恶，激动，冷漠，中性|否
阳光青年（多情感）|zh_male_yangguangqingnian_emo_v2_mars_bigtts|中文|开心，悲伤，生气，恐惧，激动，冷漠，中性|否
魅力女友（多情感）|zh_female_meilinvyou_emo_v2_mars_bigtts|中文|悲伤，恐惧，中性|否
爽快思思（多情感）|zh_female_shuangkuaisisi_emo_v2_mars_bigtts|中文,英式英语|开心，悲伤，生气，惊讶，激动，冷漠，中性|否
Candice|en_female_candice_emo_v2_mars_bigtts|美式英语|深情、愤怒、ASMR、对话/闲聊、兴奋、愉悦、中性、温暖|否
Serena|en_female_skye_emo_v2_mars_bigtts|美式英语|深情、愤怒、ASMR、对话/闲聊、兴奋、愉悦、中性、悲伤、温暖|否
Glen|en_male_glen_emo_v2_mars_bigtts|美式英语|深情、愤怒、ASMR、对话/闲聊、深情、兴奋、愉悦、中性、悲伤、温暖|否
Sylus|en_male_sylus_emo_v2_mars_bigtts|美式英语|深情、愤怒、ASMR、权威、对话/闲聊、兴奋、愉悦、中性、悲伤、温暖|否
Corey|en_male_corey_emo_v2_mars_bigtts|英式英语|愤怒、ASMR、权威、对话/闲聊、深情、兴奋、愉悦、中性、悲伤、温暖|否
Nadia|en_female_nadia_tips_emo_v2_mars_bigtts|英式英语|深情、愤怒、ASMR、对话/闲聊、深情、兴奋、愉悦、中性、悲伤、温暖|否
深夜播客|zh_male_shenyeboke_emo_v2_mars_bigtts|中文|惊讶、悲伤、中性、厌恶、开心、恐惧、激动、沮丧、冷漠、生气|猫箱|否',
		
	'教育场景' => 
'Tina老师|zh_female_yingyujiaoyu_mars_bigtts|中文,英式英语|是',
	
	'通用场景' => '温柔女神|ICL_zh_female_wenrounvshen_239eff5e8ffa_tob|中文|豆包|是
Vivi|zh_female_vv_mars_bigtts|中文|是
亲切女声|zh_female_qinqienvsheng_moon_bigtts|中文|豆包|是
机灵小伙|ICL_zh_male_shenmi_v1_tob|中文|StoryAi|是
元气甜妹|ICL_zh_female_wuxi_tob|中文|StoryAi|是
知心姐姐|ICL_zh_female_wenyinvsheng_v1_tob|中文|StoryAi|是
阳光阿辰|zh_male_qingyiyuxuan_mars_bigtts|中文|是
快乐小东|zh_male_xudong_conversation_wvae_bigtts|中文|豆包,Cici,web demo|是
冷酷哥哥|ICL_zh_male_lengkugege_v1_tob|中文|豆包|是
纯澈女生|ICL_zh_female_feicui_v1_tob|中文|StoryAi|是
初恋女友|ICL_zh_female_yuxin_v1_tob|中文|StoryAi|是
贴心闺蜜|ICL_zh_female_xnx_tob|中文|StoryAi|是
温柔白月光|ICL_zh_female_yry_tob|中文|StoryAi|是
炀炀|ICL_zh_male_BV705_streaming_cs_tob|中文|是
开朗学长|en_male_jason_conversation_wvae_bigtts|中文|豆包|是
魅力苏菲|zh_female_sophie_conversation_wvae_bigtts|中文|是
贴心妹妹|ICL_zh_female_yilin_tob|中文|StoryAi|是
甜美桃子|zh_female_tianmeitaozi_mars_bigtts|中文|是
清新女声|zh_female_qingxinnvsheng_mars_bigtts|中文|是
知性女声|zh_female_zhixingnvsheng_mars_bigtts|中文|是
清爽男大|zh_male_qingshuangnanda_mars_bigtts|中文|豆包|是
邻家女孩|zh_female_linjianvhai_moon_bigtts|中文|豆包、Cici|是
渊博小叔|zh_male_yuanboxiaoshu_moon_bigtts|中文|豆包、Cici、剪映|是
阳光青年|zh_male_yangguangqingnian_moon_bigtts|中文|豆包、Cici、StoryAi|是
甜美小源|zh_female_tianmeixiaoyuan_moon_bigtts|中文|豆包|是
清澈梓梓|zh_female_qingchezizi_moon_bigtts|中文|豆包|是
解说小明|zh_male_jieshuoxiaoming_moon_bigtts|中文|豆包|是
开朗姐姐|zh_female_kailangjiejie_moon_bigtts|中文|豆包|是
邻家男孩|zh_male_linjiananhai_moon_bigtts|中文|豆包|是
甜美悦悦|zh_female_tianmeiyueyue_moon_bigtts|中文|豆包|是
心灵鸡汤|zh_female_xinlingjitang_moon_bigtts|中文|豆包|是
知性温婉|ICL_zh_female_zhixingwenwan_tob|中文|猫箱|是
暖心体贴|ICL_zh_male_nuanxintitie_tob|中文|猫箱|是
开朗轻快|ICL_zh_male_kailangqingkuai_tob|中文|猫箱|是
活泼爽朗|ICL_zh_male_huoposhuanglang_tob|中文|猫箱|是
率真小伙|ICL_zh_male_shuaizhenxiaohuo_tob|中文|猫箱|是
温柔小哥|zh_male_wenrouxiaoge_mars_bigtts|中文|是
灿灿/Shiny|zh_female_cancan_mars_bigtts|中文,美式英语|是
爽快思思/Skye|zh_female_shuangkuaisisi_moon_bigtts|中文,美式英语|豆包、Cici、web demo|是
温暖阿虎/Alvin|zh_male_wennuanahu_moon_bigtts|中文,美式英语|豆包、Cici|是
少年梓辛/Brayan|zh_male_shaonianzixin_moon_bigtts|中文,美式英语|豆包、Cici、剪映|是',
	
	'通用场景、S2S-SC' => 
'温柔文雅|ICL_zh_female_wenrouwenya_tob|中文|猫箱|是',
		
	'P仿音' => 
'沪普男|zh_male_hupunan_mars_bigtts|仅中文|豆包|是
鲁班七号|zh_male_lubanqihao_mars_bigtts|仅中文|抖音,剪映,豆包|是
林潇|zh_female_yangmi_mars_bigtts|仅中文|剪映,抖音,豆包|是
玲玲姐姐|zh_female_linzhiling_mars_bigtts|仅中文|剪映,抖音,豆包|是
春日部姐姐|zh_female_jiyejizi2_mars_bigtts|仅中文|抖音,剪映,豆包|是
唐僧|zh_male_tangseng_mars_bigtts|仅中文|抖音,豆包|是
庄周|zh_male_zhuangzhou_mars_bigtts|仅中文|剪映,抖音|是
猪八戒|zh_male_zhubajie_mars_bigtts|仅中文|剪映订阅,火山TOB-TTS,豆包|是
感冒电音姐姐|zh_female_ganmaodianyin_mars_bigtts|仅中文|剪映,抖音|是
直率英子|zh_female_naying_mars_bigtts|仅中文|剪映,抖音,豆包|是
女雷神|zh_female_leidian_mars_bigtts|仅中文|剪映,豆包|是',

	'趣味口音' => 
'粤语小溏|zh_female_yueyunv_mars_bigtts|中文|是
豫州子轩|zh_male_yuzhouzixuan_moon_bigtts|中文-河南口音|豆包|是
呆萌川妹|zh_female_daimengchuanmei_moon_bigtts|中文-四川口音|豆包、Cici|是
广西远舟|zh_male_guangxiyuanzhou_moon_bigtts|中文-广西口音|豆包|是
双节棍小哥|zh_male_zhoujielun_emo_v2_mars_bigtts|中文-台湾口音|抖音,剪映,豆包|否
湾湾小何|zh_female_wanwanxiaohe_moon_bigtts|中文-台湾口音|豆包、Cici|是
湾区大叔|zh_female_wanqudashu_moon_bigtts|中文-广东口音|豆包、Cici|是
广州德哥|zh_male_guozhoudege_moon_bigtts|中文-广东口音|豆包、Cici|是
浩宇小哥|zh_male_haoyuxiaoge_moon_bigtts|中文-青岛口音|豆包|是
北京小爷|zh_male_beijingxiaoye_moon_bigtts|中文-北京口音|豆包|是
京腔侃爷/Harmony|zh_male_jingqiangkanye_moon_bigtts|中文-北京口音,美式英语|豆包、Cici、web demo|是
妹坨洁儿|zh_female_meituojieer_moon_bigtts|中文-长沙口音|豆包、剪映|是',

	'角色扮演' =>
'纯真少女|ICL_zh_female_chunzhenshaonv_e588402fb8ad_tob|中文|豆包|是
奶气小生|ICL_zh_male_xiaonaigou_edf58cf28b8b_tob|中文|豆包|是
精灵向导|ICL_zh_female_jinglingxiangdao_1beb294a9e3e_tob|中文|豆包|是
闷油瓶小哥|ICL_zh_male_menyoupingxiaoge_ffed9fc2fee7_tob|中文|豆包|是
黯刃秦主|ICL_zh_male_anrenqinzhu_cd62e63dcdab_tob|中文|豆包|是
霸道总裁|ICL_zh_male_badaozongcai_v1_tob|中文|是
妩媚可人|ICL_zh_female_ganli_v1_tob|中文|StoryAi|是
邪魅御姐|ICL_zh_female_xiangliangya_v1_tob|中文|StoryAi|是
嚣张小哥|ICL_zh_male_ms_tob|中文|StoryAi|是
油腻大叔|ICL_zh_male_you_tob|中文|StoryAi|是
孤傲公子|ICL_zh_male_guaogongzi_v1_tob|中文|豆包|是
胡子叔叔|ICL_zh_male_huzi_v1_tob|中文|StoryAi|是
性感魅惑|ICL_zh_female_luoqing_v1_tob|中文|StoryAi|是
病弱公子|ICL_zh_male_bingruogongzi_tob|中文|豆包|是
邪魅女王|ICL_zh_female_bingjiao3_tob|中文|StoryAi|是
傲慢青年|ICL_zh_male_aomanqingnian_tob|中文|是
醋精男生|ICL_zh_male_cujingnansheng_tob|中文|是
爽朗少年|ICL_zh_male_shuanglangshaonian_tob|中文|是
撒娇男友|ICL_zh_male_sajiaonanyou_tob|中文|是
温柔男友|ICL_zh_male_wenrounanyou_tob|中文|是
温顺少年|ICL_zh_male_wenshunshaonian_tob|中文|是
粘人男友|ICL_zh_male_naigounanyou_tob|中文|是
撒娇男生|ICL_zh_male_sajiaonansheng_tob|中文|是
活泼男友|ICL_zh_male_huoponanyou_tob|中文|是
甜系男友|ICL_zh_male_tianxinanyou_tob|中文|是
活力青年|ICL_zh_male_huoliqingnian_tob|中文|是
开朗青年|ICL_zh_male_kailangqingnian_tob|中文|是
冷漠兄长|ICL_zh_male_lengmoxiongzhang_tob|中文|是
天才同桌|ICL_zh_male_tiancaitongzhuo_tob|中文|是
翩翩公子|ICL_zh_male_pianpiangongzi_tob|中文|是
懵懂青年|ICL_zh_male_mengdongqingnian_tob|中文|是
冷脸兄长|ICL_zh_male_lenglianxiongzhang_tob|中文|是
病娇少年|ICL_zh_male_bingjiaoshaonian_tob|中文|是
病娇男友|ICL_zh_male_bingjiaonanyou_tob|中文|是
病弱少年|ICL_zh_male_bingruoshaonian_tob|中文|是
意气少年|ICL_zh_male_yiqishaonian_tob|中文|是
干净少年|ICL_zh_male_ganjingshaonian_tob|中文|是
冷漠男友|ICL_zh_male_lengmonanyou_tob|中文|是
精英青年|ICL_zh_male_jingyingqingnian_tob|中文|是
热血少年|ICL_zh_male_rexueshaonian_tob|中文|是
清爽少年|ICL_zh_male_qingshuangshaonian_tob|中文|是
中二青年|ICL_zh_male_zhongerqingnian_tob|中文|是
凌云青年|ICL_zh_male_lingyunqingnian_tob|中文|是
自负青年|ICL_zh_male_zifuqingnian_tob|中文|是
不羁青年|ICL_zh_male_bujiqingnian_tob|中文|是
儒雅君子|ICL_zh_male_ruyajunzi_tob|中文|是
低音沉郁|ICL_zh_male_diyinchenyu_tob|中文|是
冷脸学霸|ICL_zh_male_lenglianxueba_tob|中文|是
儒雅总裁|ICL_zh_male_ruyazongcai_tob|中文|是
深沉总裁|ICL_zh_male_shenchenzongcai_tob|中文|是
小侯爷|ICL_zh_male_xiaohouye_tob|中文|是
孤高公子|ICL_zh_male_gugaogongzi_tob|中文|是
仗剑君子|ICL_zh_male_zhangjianjunzi_tob|中文|是
温润学者|ICL_zh_male_wenrunxuezhe_tob|中文|是
亲切青年|ICL_zh_male_qinqieqingnian_tob|中文|是
温柔学长|ICL_zh_male_wenrouxuezhang_tob|中文|是
高冷总裁|ICL_zh_male_gaolengzongcai_tob|中文|是
冷峻高智|ICL_zh_male_lengjungaozhi_tob|中文|是
孱弱少爷|ICL_zh_male_chanruoshaoye_tob|中文|是
自信青年|ICL_zh_male_zixinqingnian_tob|中文|是
青涩青年|ICL_zh_male_qingseqingnian_tob|中文|是
学霸同桌|ICL_zh_male_xuebatongzhuo_tob|中文|是
冷傲总裁|ICL_zh_male_lengaozongcai_tob|中文|是
元气少年|ICL_zh_male_yuanqishaonian_tob|中文|是
洒脱青年|ICL_zh_male_satuoqingnian_tob|中文|是
直率青年|ICL_zh_male_zhishuaiqingnian_tob|中文|是
斯文青年|ICL_zh_male_siwenqingnian_tob|中文|是
俊逸公子|ICL_zh_male_junyigongzi_tob|中文|是
仗剑侠客|ICL_zh_male_zhangjianxiake_tob|中文|是
机甲智能|ICL_zh_male_jijiaozhineng_tob|中文|是
奶气萌娃|zh_male_naiqimengwa_mars_bigtts|中文|剪映、豆包|是
婆婆|zh_female_popo_mars_bigtts|中文|剪映C端、抖音、豆包|是
高冷御姐|zh_female_gaolengyujie_moon_bigtts|中文|豆包、Cici|是
傲娇霸总|zh_male_aojiaobazong_moon_bigtts|中文|豆包|是
魅力女友|zh_female_meilinvyou_moon_bigtts|中文|豆包、剪映|是
深夜播客|zh_male_shenyeboke_moon_bigtts|中文|豆包|是
柔美女友|zh_female_sajiaonvyou_moon_bigtts|中文|豆包、剪映|是
撒娇学妹|zh_female_yuanqinvyou_moon_bigtts|中文|豆包、剪映|是
病弱少女|ICL_zh_female_bingruoshaonv_tob|中文|是
活泼女孩|ICL_zh_female_huoponvhai_tob|中文|是
东方浩然|zh_male_dongfanghaoran_moon_bigtts|中文|豆包|是
绿茶小哥|ICL_zh_male_lvchaxiaoge_tob|中文|StoryAi、猫箱|是
娇弱萝莉|ICL_zh_female_jiaoruoluoli_tob|中文|猫箱|是
冷淡疏离|ICL_zh_male_lengdanshuli_tob|中文|猫箱|是
憨厚敦实|ICL_zh_male_hanhoudunshi_tob|中文|猫箱|是
活泼刁蛮|ICL_zh_female_huopodiaoman_tob|中文|猫箱|是
固执病娇|ICL_zh_male_guzhibingjiao_tob|中文|猫箱|是
撒娇粘人|ICL_zh_male_sajiaonianren_tob|中文|猫箱|是
傲慢娇声|ICL_zh_female_aomanjiaosheng_tob|中文|猫箱|是
潇洒随性|ICL_zh_male_xiaosasuixing_tob|中文|猫箱|是
诡异神秘|ICL_zh_male_guiyishenmi_tob|中文|猫箱|是
儒雅才俊|ICL_zh_male_ruyacaijun_tob|中文|猫箱|是
正直青年|ICL_zh_male_zhengzhiqingnian_tob|中文|StoryAi、猫箱|是
娇憨女王|ICL_zh_female_jiaohannvwang_tob|中文|StoryAi、猫箱|是
病娇萌妹|ICL_zh_female_bingjiaomengmei_tob|中文|猫箱|是
青涩小生|ICL_zh_male_qingsenaigou_tob|中文|猫箱|是
纯真学弟|ICL_zh_male_chunzhenxuedi_tob|中文|豆包、猫箱|是
优柔帮主|ICL_zh_male_youroubangzhu_tob|中文|猫箱|是
优柔公子|ICL_zh_male_yourougongzi_tob|中文|豆包、猫箱|是
调皮公主|ICL_zh_female_tiaopigongzhu_tob|中文|猫箱|是
贴心男友|ICL_zh_male_tiexinnanyou_tob|中文|豆包、猫箱|是
少年将军|ICL_zh_male_shaonianjiangjun_tob|中文|豆包、猫箱|是
病娇哥哥|ICL_zh_male_bingjiaogege_tob|中文|豆包、猫箱|是
学霸男同桌|ICL_zh_male_xuebanantongzhuo_tob|中文|豆包、猫箱|是
幽默叔叔|ICL_zh_male_youmoshushu_tob|中文|豆包、猫箱|是
假小子|ICL_zh_female_jiaxiaozi_tob|中文|豆包、猫箱|是
温柔男同桌|ICL_zh_male_wenrounantongzhuo_tob|中文|豆包、猫箱|是
幽默大爷|ICL_zh_male_youmodaye_tob|中文|豆包、猫箱|是
枕边低语|ICL_zh_male_asmryexiu_tob|中文|抖音|是
神秘法师|ICL_zh_male_shenmifashi_tob|中文|豆包、猫箱|是
娇喘女声|zh_female_jiaochuan_mars_bigtts|仅中文|剪映,抖音|是
开朗弟弟|zh_male_livelybro_mars_bigtts|仅中文|剪映,抖音|是
谄媚女声|zh_female_flattery_mars_bigtts|仅中文|剪映,抖音|是
冷峻上司|ICL_zh_male_lengjunshangsi_tob|中文|豆包、猫箱|是
寡言小哥|ICL_zh_male_xiaoge_v1_tob|中文|猫箱|是
清朗温润|ICL_zh_male_renyuwangzi_v1_tob|中文|猫箱|是
潇洒随性|ICL_zh_male_xiaosha_v1_tob|中文|猫箱|是
清冷矜贵|ICL_zh_male_liyisheng_v1_tob|中文|猫箱|是
沉稳优雅|ICL_zh_male_qinglen_v1_tob|中文|猫箱|是
清逸苏感|ICL_zh_male_chongqingzhanzhan_v1_tob|中文|猫箱|是
温柔内敛|ICL_zh_male_xingjiwangzi_v1_tob|中文|猫箱|是
低沉缱绻|ICL_zh_male_sigeshiye_v1_tob|中文|猫箱|是
蓝银草魂师|ICL_zh_male_lanyingcaohunshi_v1_tob|中文|猫箱|是
清冷高雅|ICL_zh_female_liumengdie_v1_tob|中文|猫箱|是
甜美娇俏|ICL_zh_female_linxueying_v1_tob|中文|猫箱|是
柔骨魂师|ICL_zh_female_rouguhunshi_v1_tob|中文|猫箱|是
甜美活泼|ICL_zh_female_tianmei_v1_tob|中文|猫箱|是
成熟温柔|ICL_zh_female_chengshu_v1_tob|中文|猫箱|是
贴心闺蜜|ICL_zh_female_xnx_v1_tob|中文|猫箱|是
温柔白月光|ICL_zh_female_yry_v1_tob|中文|猫箱|是
高冷沉稳|zh_male_bv139_audiobook_ummv3_bigtts|中文|猫箱|是',
	
	'角色扮演' =>
'理性圆子|ICL_zh_female_lixingyuanzi_cs_tob|中文|是
清甜桃桃|ICL_zh_female_qingtiantaotao_cs_tob|中文|是
清晰小雪|ICL_zh_female_qingxixiaoxue_cs_tob|中文|是
清甜莓莓|ICL_zh_female_qingtianmeimei_cs_tob|中文|是
开朗婷婷|ICL_zh_female_kailangtingting_cs_tob|中文|是
清新沐沐|ICL_zh_male_qingxinmumu_cs_tob|中文|是
爽朗小阳|ICL_zh_male_shuanglangxiaoyang_cs_tob|中文|是
清新波波|ICL_zh_male_qingxinbobo_cs_tob|中文|是
温婉珊珊|ICL_zh_female_wenwanshanshan_cs_tob|中文|是
甜美小雨|ICL_zh_female_tianmeixiaoyu_cs_tob|中文|是
热情艾娜|ICL_zh_female_reqingaina_cs_tob|中文|是
甜美小橘|ICL_zh_female_tianmeixiaoju_cs_tob|中文|是
沉稳明仔|ICL_zh_male_chenwenmingzai_cs_tob|中文|是
亲切小卓|ICL_zh_male_qinqiexiaozhuo_cs_tob|中文|是
灵动欣欣|ICL_zh_female_lingdongxinxin_cs_tob|中文|是
乖巧可儿|ICL_zh_female_guaiqiaokeer_cs_tob|中文|是
暖心茜茜|ICL_zh_female_nuanxinqianqian_cs_tob|中文|是
软萌团子|ICL_zh_female_ruanmengtuanzi_cs_tob|中文|是
阳光洋洋|ICL_zh_male_yangguangyangyang_cs_tob|中文|是
软萌糖糖|ICL_zh_female_ruanmengtangtang_cs_tob|中文|是
秀丽倩倩|ICL_zh_female_xiuliqianqian_cs_tob|中文|是
开心小鸿|ICL_zh_female_kaixinxiaohong_cs_tob|中文|是
轻盈朵朵|ICL_zh_female_qingyingduoduo_cs_tob|中文|是
暖阳女声|zh_female_kefunvsheng_mars_bigtts|仅中文|是',
	
	'视频配音' => 
'悠悠君子|zh_male_M100_conversation_wvae_bigtts|中文|豆包,Cici,web demo|是
文静毛毛|zh_female_maomao_conversation_wvae_bigtts|中文|豆包,web demo|是
倾心少女|ICL_zh_female_qiuling_v1_tob|中文|StoryAi|是
醇厚低音|ICL_zh_male_buyan_v1_tob|中文|StoryAi|是
咆哮小哥|ICL_zh_male_BV144_paoxiaoge_v1_tob|中文|StoryAi|是
和蔼奶奶|ICL_zh_female_heainainai_tob|中文|是
邻居阿姨|ICL_zh_female_linjuayi_tob|中文|是
温柔小雅|zh_female_wenrouxiaoya_moon_bigtts|中文|豆包|是
天才童声|zh_male_tiancaitongsheng_mars_bigtts|中文|是
猴哥|zh_male_sunwukong_mars_bigtts|中文|是
熊二|zh_male_xionger_mars_bigtts|中文|抖音、剪映C端、豆包|是
佩奇猪|zh_female_peiqi_mars_bigtts|中文|抖音、剪映订阅、豆包|是
武则天|zh_female_wuzetian_mars_bigtts|中文|剪映|是
顾姐|zh_female_gujie_mars_bigtts|中文|抖音、剪映C端|是
樱桃丸子|zh_female_yingtaowanzi_mars_bigtts|中文|剪映订阅、抖音、豆包|是
广告解说|zh_male_chunhui_mars_bigtts|中文|剪映|是
少儿故事|zh_female_shaoergushi_mars_bigtts|中文|是
四郎|zh_male_silang_mars_bigtts|中文|抖音、剪映C端、豆包|是
俏皮女声|zh_female_qiaopinvsheng_mars_bigtts|中文|是
懒音绵宝|zh_male_lanxiaoyang_mars_bigtts|中文|是
亮嗓萌仔|zh_male_dongmanhaimian_mars_bigtts|中文|是
磁性解说男声/Morgan|zh_male_jieshuonansheng_mars_bigtts|中文,美式英语|抖音、剪映|是
鸡汤妹妹/Hope|zh_female_jitangmeimei_mars_bigtts|中文,美式英语|抖音、豆包|是
贴心女声/Candy|zh_female_tiexinnvsheng_mars_bigtts|中文,美式英语|是
萌丫头/Cutey|zh_female_mengyatou_mars_bigtts|中文,美式英语|是',
);