<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'PclZip' => $vendorDir . '/pclzip/pclzip/pclzip.lib.php',
);
